sudo: false
language: python
python:
    - "2.6"
    - "2.7"
    - "3.5"
env:
    - TORNADO_VERSION=4.5.3
install: 
    - "pip install -r requirements.txt -r requirements-tests.txt --use-mirrors"
    - "pip install tornado==$TORNADO_VERSION"
# only build master and PRs, not every branch
branches:
    only:
        - master
script: "testify -v tests"
matrix:
    fast_finish: true
